module.exports = {
  title: "YOUR:BLOG:NAME",
  headerTitle: "YOUR:<em style='color:#ed6c02'>BLOG</em>:NAME",
  headerSubTitle: "",
  copyright: "©YOUR:BLOG:NAME",
  author: "rundevelrun",
  siteUrl: "https://6developer.com/",
  description: "Hi, Nice to meet you !",
  links: {
    github: "https://github.com/rundevelrun",
    linkedIn: "https://linkedin.com",
    facebook: "https://www.facebook.com",
    twitter: "https://twitter.com",
    x: "https://x.com",
    instagram: "https://www.instagram.com/niphyang.flow",
    medium: "https://medium.com",
    blogger: "https://blogger.com",
    email: "mailto:niphyang@naver.com",
    resume: "https://6developer.com",
    link: "https://6developer.com",
  },
  // See https://giscus.app/
  giscus: {
    repo: "devHudi/gatsby-starter-hoodie",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
